name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
      - name: Deploy
        uses: up9cloud/action-rsync@v1.3
        env:
          HOST: four.garin.xyz
          USER: pi
          ARGS: -a
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SOURCE: dist/
          TARGET: /var/www/html/resume-website/
