# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: Lint
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: lint # will run `yarn lint` command
      - name: Build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
